name: Hello World
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-slim
    steps:
      - name: Hello stop
        run: |
          echo "This is running first step"
          echo "This is running second step"
          
