name: Hello World
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-slim
    steps:
      - name: Hello stop
        run: |
          echo "This ran step-1"
          echo "This ran step-2"
          
